In [1]:
import numpy as np 

A = np.array([[56.0, 0.0, 4.4, 68.0], 
              [1.2, 104.0, 52.0, 8.0], 
              [1.8, 135.0, 99.0, 0.9]])

print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [2]:
cal = A.sum(axis = 0)  # sum columnwise
print(cal)

[  59.   239.   155.4   76.9]


In [6]:
percentage = 100 * A / (cal.reshape(1,4))  # use reshape is optional; recommend to use when not sure about the dimension
print(percentage)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [5]:
100 * A / cal

array([[ 94.91525424,   0.        ,   2.83140283,  88.42652796],
       [  2.03389831,  43.51464435,  33.46203346,  10.40312094],
       [  3.05084746,  56.48535565,  63.70656371,   1.17035111]])

In [9]:
a = np.random.randn(5)
print(a)

[ 0.92757353  0.56056957 -0.5661748  -0.18297256  0.41000106]


In [10]:
print(a.shape)

(5,)


In [11]:
print(a.T)

[ 0.92757353  0.56056957 -0.5661748  -0.18297256  0.41000106]


In [12]:
print(np.dot(a, a.T))

1.69676462454


In [20]:
# Recommendation: not to use data structure like (5, )  "rank 1 array"

In [14]:
a = np.random.randn(5, 1)
print(a)
print(a.T)

[[ 0.61238919]
 [-0.96913673]
 [ 0.22078921]
 [-0.55115525]
 [ 0.29510021]]
[[ 0.61238919 -0.96913673  0.22078921 -0.55115525  0.29510021]]


In [15]:
print(np.dot(a, a.T))  # Return the outer product

[[ 0.37502052 -0.59348886  0.13520893 -0.33752152  0.18071618]
 [-0.59348886  0.93922601 -0.21397494  0.5341448  -0.28599245]
 [ 0.13520893 -0.21397494  0.04874788 -0.12168913  0.06515494]
 [-0.33752152  0.5341448  -0.12168913  0.30377211 -0.16264603]
 [ 0.18071618 -0.28599245  0.06515494 -0.16264603  0.08708413]]


In [16]:
assert(a.shape == (5, 1))

In [17]:
a.shape

(5, 1)